export const homeObjOne = {
	id: 'Activités',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Activites',
	headline: "Création d'un club de développement durable",
	description: "La première action dans le collège ERRACHIDIA Mourouj 3 pour la création d'un club de développement durable ayant pour but de sensibiliser et promouvoir les 17 objectifs de développement durable. Les thèmes qui ont été développés sur une période de trois mois ont été de faire connaître les 17 objectifs de développement durable 2030 aux élèves afin de les sensibiliser à l'importance de ces objectifs et comment impliquer la génération actuelle pour jouer le rôle d'acteur majeur du changement.",
	imgStart: true,
	img: require('../../images/goals.jpg').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
	needed: false
}
export const homeObjOne1 = {
	id: 'Activités',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Activités',
	headline: "Forum : Le Développement Durale et l'Economie Sociale et Solidaire Leviers De Croissance",
	description: "En Avril 2019 le CSPDD a organisé à la Cité Des sciences un forum avec plusieurs invités pour débattre de la réalité et perspectives de l'agenda 2030 et de l'économie sociale et solidaire. Plusieurs associations de la société civile étaient présentes ainsi qu'un professeur et militant de L' ESS Mr Lotfi Ben Aissa.",
	imgStart: true,
	img: require('../../images/forum.jpg').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
	needed: false

}
export const homeObjOne2 = {
	id: 'Activités',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Activités',
	headline: "Action au niveau de l'école  SIDI MOUSSA au SERS gouvernorat du KEF",
	description: "Il s'agit d'une action au niveau de l'infrastructure de l'école et la création d'un club de développement durable en milieu rural. Au niveau de l'école, nous avons pu contribuer à élaborer des travaux de peinture et de construction de quatorze fenêtres pour la protection des classes. D'autres activités sont programmées pour l'année 2022 au niveau de l'infrastructure et la création  d'un  club audio-visuel ainsi que la construction d'une cantine et d'une bibliothèque.",
	imgStart: true,
	img: require('../../images/ecole.jpg').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
	needed: false
}
export const homeObjOne3 = {
	id: 'Activités',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Activités',
	headline: "Conférence sur les indicateurs des 17 objectifs du développement durable",
	description: "Suite à une invitation de l'Institut National Des Statistiques, le Président du CSPDD a présenté  une conférence sur la préparation des indicateurs des ODD et sur le rôle de la société civile dans la mise en place de la plateforme avec toutes les parties prenantes. Cette occasion nous a permis d'atteindre notre objectif d'être parmi les acteurs pour la mise en place des indicateurs des ODD. Le résultat a été bénéfique, notre association a été sollicitée par plusieurs organismes pour animer des conférences sur l'agenda 2030.",
	imgStart: true,
	img: require('../../images/Capture.PNG').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
	needed: false
}
export const homeObjOne4 = {
	id: 'Activités',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Activités',
	headline: "Séminaire sur Le Développement Durable ",
	description: "Grâce à l'initiative de Dr Rabiaa Romdhane et du doyen de la FSEG Mahdia, Pr Faouzi Sboui, nous avons pu présenter un séminaire pour les étudiants de première année Master sous le thème : Le Développement Durable, Réalités et Perspectives. ",
	imgStart: true,
	img: require('../../images/seminaire.jpg').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
	needed: false
}
export const homeObjTwo = {
	id: 'NosProjets',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Nos Projets',
	headline: 'De mon école, à ma ville, à mon lac et à ma méditerranée',
	description: "Dans le cadre du programme intégré pour la dépollution de la région du lac de Bizerte, l'action de sensibilisation et d'éducation environnementale intitulée (De mon école, à ma ville, à mon lac et à ma méditerranée) est mise en œuvre par le Centre Stratégique Pour La Promotion Du Développement Durable CSPDD. Cette action sera axée sur la sensibilisation au respect de l'environnement dans le but de construire une culture citoyenne basée sur la promotion de l'agenda 2030 dans toutes ses composantes : environnementale, sociétale et économique. Les activités de cette action  seront  réalisées dans les établissements scolaires des  régions de Menzel Jemil et Menzel Bourguiba. L'objectif ultime, à travers ces activités, est d'éveiller les consciences pour espérer des changements de comportement des jeunes, les futurs décideurs de demain. La durée de l'action est de 18 mois.",
	buttonLabel: 'Savoir Plus',
	imgStart: true,
	img: require('../../images/lotfi.jpg').default,
	alt: 'hello',
	dark: false,
	primary: false,
	darkText: true,
	needed: false,
	link: 'https://www.facebook.com/De-mon-%C3%A9cole-%C3%A0-ma-ville-%C3%A0-mon-lac-et-%C3%A0-ma-m%C3%A9diterran%C3%A9e-101988748682301'
}
export const projectTwo = {
	id: 'NosProjets',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Nos Projets',
	headline: 'Voler De Ses Propres Ailes',
	description: "Le Centre Stratégique pour la Promotion du Développement Durable a le plaisir de vous informer que son projet « Voler de ses propres ailes » est retenu suite à l’appel à candidature « Renforcement de la société civile émergente en Tunisie-  Fonds réactif et d’opportunités Mai 2022 », mis en œuvre par un consortium formé par Oxfam et ses partenaires. Le présent projet est financé par l’Union Européenne avec un montant de 48 180,000 TND.Il vise le renforcement de capacités de 4 associations tunisiennes dans la région de Ben Arous qui ont survécu aux conditions difficiles imposées par la pandémie du Covid-19 ou qui ont été récemment constituées et dont la viabilité est réellement menacée. Il s’étale sur cinq mois et propose un programme de formation dans différents domaines notamment la restructuration et la réorganisation des associations, la pollution et les problèmes environnementaux de la région de Ben Arous, la démocratie participative, l’économie sociale et solidaire, le financement et les procédures légales et administratives. Des visites sur le terrain sont également prévues.",
	buttonLabel: 'Savoir Plus',
	imgStart: true,
	img: require('../../images/project2.jpg').default,
	alt: 'hello',
	dark: false,
	primary: false,
	darkText: true,
	needed: false,
	link: 'https://www.facebook.com/De-mon-%C3%A9cole-%C3%A0-ma-ville-%C3%A0-mon-lac-et-%C3%A0-ma-m%C3%A9diterran%C3%A9e-101988748682301'
}
export const homeObjTwo2 = {
	id: 'NosProjets',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	imgStart: false,
	img: require('../../images/annonce.jpg').default,
	alt: 'hello',
	dark: false,
	primary: false,
	darkText: true,
	needed: false,
	link: 'https://www.facebook.com/De-mon-%C3%A9cole-%C3%A0-ma-ville-%C3%A0-mon-lac-et-%C3%A0-ma-m%C3%A9diterran%C3%A9e-101988748682301'
}

export const article1 = {
	id: 'Activités',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'مقال',
	headline: "إزالة التلوث من بحيرة بنزرت : المركز الاستراتيجي للنهوض بالتنمية المستدامة يعدّ برنامجا طموحا يستهدف التلاميذ",
	description: "يعلن المركز الاستراتيجي  للنهوض بالتنمية المستدامة أن مشروعه ( من مدرستي  إلى مدينتي   إلى بحيرتي وإلى بحري الأبيض المتوسط ) قد تم اختياره بعد عملية دعوة لتقديم المشاريع  : دعم عمليات  التحسيس و التوعية  والتربية  البيئية  في ولاية بنزرت  برنامج EcoPact.",
	buttonLabel: 'أكمل القراءة',
	imgStart: true,
	img: require('../../images/lotfi.jpg').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
	needed: true,
	link: 'https://ar.espacemanager.com/%D8%A5%D8%B2%D8%A7%D9%84%D8%A9-%D8%A7%D9%84%D8%AA%D9%84%D9%88%D8%AB-%D9%85%D9%86-%D8%A8%D8%AD%D9%8A%D8%B1%D8%A9-%D8%A8%D9%86%D8%B2%D8%B1%D8%AA-%D8%A7%D9%84%D9%85%D8%B1%D9%83%D8%B2-%D8%A7%D9%84%D8%A7%D8%B3%D8%AA%D8%B1%D8%A7%D8%AA%D9%8A%D8%AC%D9%8A-%D9%84%D9%84%D9%86%D9%87%D9%88%D8%B6-%D8%A8%D8%A7%D9%84%D8%AA%D9%86%D9%85%D9%8A%D8%A9-%D8%A7%D9%84%D9%85%D8%B3%D8%AA%D8%AF%D8%A7%D9%85%D8%A9-%D9%8A%D8%B9%D8%AF%D9%91-%D8%A8%D8%B1%D9%86%D8%A7%D9%85%D8%AC%D8%A7-%D8%B7%D9%85%D9%88%D8%AD%D8%A7-%D9%8A%D8%B3%D8%AA%D9%87%D8%AF%D9%81?fbclid=IwAR02F9fEa5Svqcz2vVyaoxDV0WCZQSIO6Yrb1eGO82fERxbwVc4a6RWejtE'
}

export const article2 = {
	id: 'Articles',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'Articles',
	headline: "Annonce d'information pour le public et les parties prenantes sur le financement du projet",
	description: "Le Centre Stratégique Pour La Promotion Du Développement Durable a l'honneur de vous informer que son projet « De mon école, à ma ville, à mon Lac et à ma méditerranée» est retenu suite au processus de l'Appel à propositions : Appui aux actions de sensibilisation et d'éducation environnementale dans le gouvernorat de Bizerte-Programme EcoPact.",
	buttonLabel: 'Savoir Plus',
	imgStart: true,
	img: require('../../images/ecopact.jpg').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
	needed: true,
	link: 'https://www.espacemanager.com/education-et-sensibilisation-des-eleves-la-protection-de-lenvironnement.html?fbclid=IwAR26FDo5lb50FPUXraBNFsY5X17_Q0KEVLMQyC-rG2FADHXkOb_ZLwvEfGA'
}

export const descriptionProjet = {
	id: 'NosProjets',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'PHASE DE DEMARRAGE',
	headline: "OS0 : Dissémination et adhésion à l’action",
	description: "A0 : Encadrement et dissémination de l’action" + "    • A0.1. Diffuser l’information sur l’action A0.2.  Inscrire et former les groupes de travail (un groupe/établissement scolaire prévu). A0.3.   Créer un site web et une page Facebook pour le projet.",
	buttonLabel: 'Savoir Plus',
	imgStart: true,
	img: require('../../images/ecopact.jpg').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
	needed: true,
	link: 'https://www.espacemanager.com/education-et-sensibilisation-des-eleves-la-protection-de-lenvironnement.html?fbclid=IwAR26FDo5lb50FPUXraBNFsY5X17_Q0KEVLMQyC-rG2FADHXkOb_ZLwvEfGA'
}
export const descriptionProjet2 = {
	id: 'NosProjets',
	lightBg: true,
	lightText: false,
	lightTextDesc: false,
	topLine: 'PHASE DE MISE EN ŒUVRE DES ACTIVITES',
	headline: "OS1 : -Découvrir son territoire - Stimuler l’action et la participation- Porter un regard critique et autonome sur la situation environnementale des quartiers/villes limitrophes du Lac",
	description: "A1 : Enquête ou sondage d’opinions et débats A1.1. Développer des aptitudes pour l’enquête et d’attitudes d’écoute par la formation  A1.2. Réaliser une enquête d’opinions sur l’état de l’environnement dans les quartiers des élèves. A1.3. Dépouiller, discuter et débattre les résultats obtenus de l’enquête Cette étude pourrait être utilisée par les élèves pour instruire des projets créatifs tels que préconisé dans l’activité A3.2. ",
	buttonLabel: 'Savoir Plus',
	imgStart: true,
	img: require('../../images/ecopact.jpg').default,
	alt: 'Car',
	dark: false,
	primary: false,
	darkText: true,
	needed: true,
	link: 'https://www.espacemanager.com/education-et-sensibilisation-des-eleves-la-protection-de-lenvironnement.html?fbclid=IwAR26FDo5lb50FPUXraBNFsY5X17_Q0KEVLMQyC-rG2FADHXkOb_ZLwvEfGA'
}